/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo2;

/**
 *
 * @author ALINE
 */
public class Cap1GUI extends javax.swing.JPanel {

    /**
     * Creates new form Cap1GUI
     */
    public Cap1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspCap1 = new javax.swing.JScrollPane();
        jtaCap1 = new javax.swing.JTextArea();
        jbNextCap1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));

        jtaCap1.setEditable(false);
        jtaCap1.setBackground(new java.awt.Color(0, 204, 204));
        jtaCap1.setColumns(20);
        jtaCap1.setFont(new java.awt.Font("Nyala", 0, 29)); // NOI18N
        jtaCap1.setRows(5);
        jtaCap1.setText("\n     Aufa e Ehpol estavam prontos para mais uma aventura nas profundezas do oceano, mas dessa vez, usariam o \n  novo feitiço que aprenderam na academia para respirar em baixo d'agua. Mergulharam e se separaram como de\n  costume, super empolgados, pois dessa vez conseguiriam ir mais fundo. A caverna Lamda, situada na cidade de\n  Javes, nunca antes explorada por mais ninguém além deles, era um prato cheio para os curiosos e valentes \n  irmãos.\n  \n     Aufa encontrou um túnel e adentrou sem pensar duas vezes. Era difícil enxergar, mas a luz que emanava da\n  magia já bastava para ver o que estava a frente. O túnel acabou e ele encontrou uma espécie de sala subterrânea,\n  não achou nada além de algas velhas. Decepcionado, nadou de volta para a terra firme, tal qual foi sua surpresa\n  quando viu que estava acontecendo um terremoto. Olhou para trás e viu algo emergindo ao longe.\n  De início parecia uma rocha, mas conforme foi saindo da água, sua silhueta foi tomando forma. Era uma criatura\n  gigante que parecia mais com... Belta!? Não era só uma lenda? Para seu desespero, quando a criatura estava perto\n  o suficiente para ver os mínimos detalhes de seu corpo horrendo, viu seu irmão entre as garras do monstro. \n  Ficou surpreso quando o temível Belta... guardou seu irmão em uma espécie de bolso na barriga?\n     \n     Os jovens sempre sonharam em viver uma empolgante e perigosa aventura, parece que o momento chegou,\n  mas não estava sendo tão divertido quanto eles imaginavam que seria. ");
        jtaCap1.setEnabled(false);
        jtaCap1.setHighlighter(null);
        jspCap1.setViewportView(jtaCap1);

        jbNextCap1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jbNextCap1.setText("Next");
        jbNextCap1.setEnabled(false);
        jbNextCap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextCap1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspCap1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNextCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jspCap1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNextCap1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbNextCap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextCap1ActionPerformed
        //        jbNextCap1.setVisible(false);
        //        jpCap1.setVisible(false);
        //        jspCap1.setVisible(false);
        //        jtaCap1.setVisible(false);
        //jdIntro.setVisible(true);
    }//GEN-LAST:event_jbNextCap1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNextCap1;
    private javax.swing.JScrollPane jspCap1;
    private javax.swing.JTextArea jtaCap1;
    // End of variables declaration//GEN-END:variables
}
