/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo2;

/**
 *
 * @author Aluno
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FacilDificil = new javax.swing.ButtonGroup();
        jdIntro = new javax.swing.JDialog();
        jpIntro = new javax.swing.JPanel();
        jspIntro = new javax.swing.JScrollPane();
        jtaIntro = new javax.swing.JTextArea();
        jbOkIntro = new javax.swing.JButton();
        jpMenu = new javax.swing.JPanel();
        jrbFacil = new javax.swing.JRadioButton();
        jrbDificil = new javax.swing.JRadioButton();
        jbOkMenu = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jlRacLog = new javax.swing.JLabel();

        jdIntro.setTitle("Tutorial");
        jdIntro.setLocation(new java.awt.Point(500, 500));
        jdIntro.setMinimumSize(new java.awt.Dimension(700, 300));
        jdIntro.setName(""); // NOI18N
        jdIntro.setResizable(false);
        jdIntro.setSize(new java.awt.Dimension(670, 200));

        jpIntro.setBackground(new java.awt.Color(153, 255, 204));
        jpIntro.setName("Tutorial"); // NOI18N

        jtaIntro.setEditable(false);
        jtaIntro.setBackground(new java.awt.Color(153, 255, 204));
        jtaIntro.setColumns(20);
        jtaIntro.setFont(new java.awt.Font("GungsuhChe", 0, 20)); // NOI18N
        jtaIntro.setRows(5);
        jtaIntro.setText("\n    A proteção mágica nas escamas de Belta pode ser quebrada\n  a partir de golpes em lugares específicos e no momento certo.\n    Use a matemática para ajudar Aufa a atacá-lo nos lugares \n  em que o escudo está mais vulnerável em cada partida.");
        jspIntro.setViewportView(jtaIntro);

        jbOkIntro.setText("OK");
        jbOkIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkIntroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpIntroLayout = new javax.swing.GroupLayout(jpIntro);
        jpIntro.setLayout(jpIntroLayout);
        jpIntroLayout.setHorizontalGroup(
            jpIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspIntro, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpIntroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbOkIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpIntroLayout.setVerticalGroup(
            jpIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspIntro, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbOkIntro)
                .addContainerGap())
        );

        javax.swing.GroupLayout jdIntroLayout = new javax.swing.GroupLayout(jdIntro.getContentPane());
        jdIntro.getContentPane().setLayout(jdIntroLayout);
        jdIntroLayout.setHorizontalGroup(
            jdIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdIntroLayout.setVerticalGroup(
            jdIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpMenu.setBackground(new java.awt.Color(204, 204, 255));

        FacilDificil.add(jrbFacil);
        jrbFacil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbFacil.setText("Fácil");
        jrbFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbFacilActionPerformed(evt);
            }
        });

        FacilDificil.add(jrbDificil);
        jrbDificil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jrbDificil.setText("Difícil");
        jrbDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbDificilActionPerformed(evt);
            }
        });

        jbOkMenu.setBackground(new java.awt.Color(153, 255, 153));
        jbOkMenu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbOkMenu.setText("OK");
        jbOkMenu.setEnabled(false);
        jbOkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkMenuActionPerformed(evt);
            }
        });

        jbSair.setBackground(new java.awt.Color(255, 153, 153));
        jbSair.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jlRacLog.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jlRacLog.setForeground(new java.awt.Color(204, 0, 0));
        jlRacLog.setText("RAC-LOG");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDificil)
                            .addComponent(jrbFacil))
                        .addGap(172, 172, 172))
                    .addComponent(jlRacLog)
                    .addGroup(jpMenuLayout.createSequentialGroup()
                        .addComponent(jbOkMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)))
                .addContainerGap(428, Short.MAX_VALUE))
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jlRacLog)
                .addGap(80, 80, 80)
                .addComponent(jrbFacil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbDificil)
                .addGap(18, 18, 18)
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOkMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1316, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbFacilActionPerformed
        jbOkMenu.setEnabled(true);
    }//GEN-LAST:event_jrbFacilActionPerformed

    private void jrbDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbDificilActionPerformed
        jbOkMenu.setEnabled(true);
    }//GEN-LAST:event_jrbDificilActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbOkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkMenuActionPerformed
        jpMenu.setVisible(false);
        jrbDificil.setVisible(false);
        jrbFacil.setVisible(false);
        jlRacLog.setVisible(false);
        jbSair.setVisible(false);
        jbOkMenu.setVisible(false);
        //jbNextCap1.setEnabled(true);
        //jtaCap1.setEnabled(true);
    }//GEN-LAST:event_jbOkMenuActionPerformed

    private void jbOkIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkIntroActionPerformed
        dispose();
        jdIntro.setVisible(false);
//        new FasesGUI().setVisible(true);
    }//GEN-LAST:event_jbOkIntroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup FacilDificil;
    private javax.swing.JButton jbOkIntro;
    private javax.swing.JButton jbOkMenu;
    private javax.swing.JButton jbSair;
    private javax.swing.JDialog jdIntro;
    private javax.swing.JLabel jlRacLog;
    private javax.swing.JPanel jpIntro;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JRadioButton jrbDificil;
    private javax.swing.JRadioButton jrbFacil;
    private javax.swing.JScrollPane jspIntro;
    private javax.swing.JTextArea jtaIntro;
    // End of variables declaration//GEN-END:variables
}
