/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogo2;

/**
 *
 * @author Aluno
 */
public class PrologoGUI extends javax.swing.JFrame {

    /**
     * Creates new form Prologo
     */
    public PrologoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrologo = new javax.swing.JPanel();
        jbNextPrologo = new javax.swing.JButton();
        jspPrologo = new javax.swing.JScrollPane();
        jtaPrologo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prólogo");
        setResizable(false);

        jpPrologo.setBackground(new java.awt.Color(0, 204, 204));
        jpPrologo.setToolTipText("");

        jbNextPrologo.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jbNextPrologo.setText("Next");
        jbNextPrologo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextPrologoActionPerformed(evt);
            }
        });

        jtaPrologo.setEditable(false);
        jtaPrologo.setBackground(new java.awt.Color(0, 204, 204));
        jtaPrologo.setColumns(20);
        jtaPrologo.setFont(new java.awt.Font("Nyala", 0, 30)); // NOI18N
        jtaPrologo.setRows(5);
        jtaPrologo.setText("   \" Em tempos remotos, havia um poderoso feiticeiro chamado Logarim. Ele e seus ajudantes\n estavam tentando criar novas espécies de animais através da magia, mas em vez disso,\n criaram uma besta horrenda, totalmente selvagem e sedenta por sangue. Milhares de dentes\n afiados, 100m de altura, escamas duras como aço, essa era a aparência da criatura que tinha\n como único hobbie a destruição. Os aprendizes de Logarim conseguiram selar o monstro e o\n planeta Guthobbie nunca mais se esquecerá do dia em que cidades inteiras foram dizimadas\n pela criatura conhecida hoje como Belta.\"\n          Mas isso é só um conto infantil, não é mesmo? :)");
        jtaPrologo.setHighlighter(null);
        jspPrologo.setViewportView(jtaPrologo);

        javax.swing.GroupLayout jpPrologoLayout = new javax.swing.GroupLayout(jpPrologo);
        jpPrologo.setLayout(jpPrologoLayout);
        jpPrologoLayout.setHorizontalGroup(
            jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrologoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPrologoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbNextPrologo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpPrologoLayout.setVerticalGroup(
            jpPrologoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrologoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbNextPrologo)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrologo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpPrologo.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1102, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbNextPrologoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextPrologoActionPerformed
        dispose();
        new MenuGUI().setVisible(true);
    }//GEN-LAST:event_jbNextPrologoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrologoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrologoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrologoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrologoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrologoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbNextPrologo;
    private javax.swing.JPanel jpPrologo;
    private javax.swing.JScrollPane jspPrologo;
    private javax.swing.JTextArea jtaPrologo;
    // End of variables declaration//GEN-END:variables
}
